/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.atakancetinkaya.arayuz;
import com.atakancetinkaya.siniflar.*;
import javax.swing.JOptionPane;
/**
 *
 * @author ataka
 */
public class giris extends javax.swing.JFrame {

    /**
     * Creates new form giris
     */
    public giris() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_kAdi = new javax.swing.JTextField();
        txt_kSifre = new javax.swing.JPasswordField();
        btn_girisYap = new javax.swing.JButton();
        btn_iptal = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/atakancetinkaya/arayuz/library-books-interior-design-shelves-wallpaper-thumb.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ataka\\OneDrive\\Masaüstü\\KutuphaneOtomasyonu\\image\\user-icon-human-person-sign-vector-10206693_15x15.jpg")); // NOI18N
        jLabel1.setText("Kullanıcı Adı");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(130, 120, 100, 15);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\ataka\\OneDrive\\Masaüstü\\KutuphaneOtomasyonu\\image\\password_12x15.jpg")); // NOI18N
        jLabel2.setText("Şifre");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(180, 150, 50, 15);

        txt_kAdi.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(txt_kAdi);
        txt_kAdi.setBounds(250, 117, 170, 21);

        txt_kSifre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(txt_kSifre);
        txt_kSifre.setBounds(250, 150, 170, 21);

        btn_girisYap.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_girisYap.setIcon(new javax.swing.ImageIcon("C:\\Users\\ataka\\OneDrive\\Masaüstü\\KutuphaneOtomasyonu\\image\\login-icon-in-trendy-flat-style-vector-20053309_15x15.jpg")); // NOI18N
        btn_girisYap.setText("Giriş");
        btn_girisYap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_girisYapActionPerformed(evt);
            }
        });
        getContentPane().add(btn_girisYap);
        btn_girisYap.setBounds(250, 180, 80, 23);

        btn_iptal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_iptal.setIcon(new javax.swing.ImageIcon("C:\\Users\\ataka\\OneDrive\\Masaüstü\\KutuphaneOtomasyonu\\image\\single-flat-close-icon-icon-with-long-shadow-vector-2715630_15x15.jpg")); // NOI18N
        btn_iptal.setText("İptal");
        btn_iptal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_iptalActionPerformed(evt);
            }
        });
        getContentPane().add(btn_iptal);
        btn_iptal.setBounds(340, 180, 80, 23);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/atakancetinkaya/arayuz/library-books-interior-design-shelves-wallpaper-thumb.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 550, 310);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_girisYapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_girisYapActionPerformed
        boolean durum = false;//boolean veri türünde durum adında değişken tanımlayıp başlangıç değerini false yaptım
        
        girisYap gy =new girisYap();//girisYap sınıfından "gy" adında nesne oluşturdum
        
        try 
        {
            durum=gy.giris(txt_kAdi.getText(),String.valueOf(txt_kSifre.getPassword()));//"gy" nesnesini kullanarak girisYap sınıfı altındaki giris methoduna eriş ve bunu duruma ata
        } 
        catch (Exception e) 
        {
            System.out.println(e);// e yi ekrana yaz   
        }
        
        if(durum)
        {
            setVisible(false);//giris forumunu kapat
            new menu().setVisible(true);//menu formunu aç      
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Kullanıcı adı veya parola yanlış!.");//uyarı mesajı
        }
        
    }//GEN-LAST:event_btn_girisYapActionPerformed

    private void btn_iptalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_iptalActionPerformed
        setVisible(false);//formu kapat
    }//GEN-LAST:event_btn_iptalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(giris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(giris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(giris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(giris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new giris().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_girisYap;
    private javax.swing.JButton btn_iptal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txt_kAdi;
    private javax.swing.JPasswordField txt_kSifre;
    // End of variables declaration//GEN-END:variables
}
