/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.atakancetinkaya.arayuz;

import com.atakancetinkaya.siniflar.*;
import javax.swing.JOptionPane;

/**
 *
 * @author ataka
 */
public class kitapESG extends javax.swing.JFrame {

    /**
     * Creates new form kitapESG
     */
    public kitapESG() {
        initComponents();
        btn_Guncelle.setEnabled(false);
        btn_Sil.setEnabled(false);
        temizle();//temizle methodunu çalıştır.
    }
    public void temizle()
    {
        txt_id.setText("");//txt_id nin içini boşalt
        txt_adi.setText("");//txt_adi nin içini boşalt
        txt_turu.setText("");//txt_turu nin içini boşalt
        txt_yEvi.setText("");//txt_yEvi nin içini boşalt
        txt_yazar.setText("");//txt_yazar nin içini boşalt
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        txt_adi = new javax.swing.JTextField();
        txt_turu = new javax.swing.JTextField();
        txt_yEvi = new javax.swing.JTextField();
        txt_yazar = new javax.swing.JTextField();
        btn_Kaydet = new javax.swing.JButton();
        btn_Bul = new javax.swing.JButton();
        btn_Sil = new javax.swing.JButton();
        btn_Guncelle = new javax.swing.JButton();
        btn_MenuDon = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("id");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(210, 105, 11, 15);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Adı");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(201, 141, 20, 15);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Türü");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(193, 184, 28, 15);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("YayınEvi");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(172, 231, 49, 15);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Yazar");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(189, 274, 32, 15);

        txt_id.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(txt_id);
        txt_id.setBounds(239, 100, 163, 25);

        txt_adi.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(txt_adi);
        txt_adi.setBounds(239, 136, 163, 25);

        txt_turu.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(txt_turu);
        txt_turu.setBounds(239, 179, 163, 25);

        txt_yEvi.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(txt_yEvi);
        txt_yEvi.setBounds(239, 226, 163, 25);

        txt_yazar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(txt_yazar);
        txt_yazar.setBounds(239, 269, 163, 25);

        btn_Kaydet.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_Kaydet.setIcon(new javax.swing.ImageIcon("C:\\Users\\ataka\\OneDrive\\Masaüstü\\KutuphaneOtomasyonu\\image\\add_30x30.jpg")); // NOI18N
        btn_Kaydet.setText("Kaydet");
        btn_Kaydet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_KaydetActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Kaydet);
        btn_Kaydet.setBounds(471, 91, 109, 55);

        btn_Bul.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_Bul.setIcon(new javax.swing.ImageIcon("C:\\Users\\ataka\\OneDrive\\Masaüstü\\KutuphaneOtomasyonu\\image\\search_30x30.jpg")); // NOI18N
        btn_Bul.setText("Bul");
        btn_Bul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BulActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Bul);
        btn_Bul.setBounds(590, 91, 117, 55);

        btn_Sil.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_Sil.setIcon(new javax.swing.ImageIcon("C:\\Users\\ataka\\OneDrive\\Masaüstü\\KutuphaneOtomasyonu\\image\\remove_30x30.jpg")); // NOI18N
        btn_Sil.setText("Sil");
        btn_Sil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SilActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Sil);
        btn_Sil.setBounds(471, 164, 109, 55);

        btn_Guncelle.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_Guncelle.setIcon(new javax.swing.ImageIcon("C:\\Users\\ataka\\OneDrive\\Masaüstü\\KutuphaneOtomasyonu\\image\\update_30x30.jpg")); // NOI18N
        btn_Guncelle.setText("Güncelle");
        btn_Guncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_GuncelleActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Guncelle);
        btn_Guncelle.setBounds(590, 164, 117, 55);

        btn_MenuDon.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_MenuDon.setIcon(new javax.swing.ImageIcon("C:\\Users\\ataka\\OneDrive\\Masaüstü\\KutuphaneOtomasyonu\\image\\back_30x30.jpg")); // NOI18N
        btn_MenuDon.setText("Meniye Dön");
        btn_MenuDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_MenuDonActionPerformed(evt);
            }
        });
        getContentPane().add(btn_MenuDon);
        btn_MenuDon.setBounds(514, 237, 139, 57);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/atakancetinkaya/arayuz/1_757x410.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 760, 410);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_KaydetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_KaydetActionPerformed
        boolean durum=false;//boolean veri türünde durum adında değişken tanımlayıp başlangıç değerini false yaptım.
        kitaplar ke= new kitaplar();//uyeler sınıfında "ke" adında nesne oluşturdum.
        ke.setK_id(txt_id.getText());//"txt_id" oku "K_id" ya aktar.
        ke.setK_adi(txt_adi.getText());//"txt_adi" oku "K_adi" ya aktar.
        ke.setK_turu(txt_turu.getText());//"txt_turu" oku "K_turu" ya aktar.
        ke.setK_yEvi(txt_yEvi.getText());//"txt_yEvi" oku "K_yEvi" ya aktar.
        ke.setK_yazar(txt_yazar.getText());//"txt_yazar" oku "K_yazar" ya aktar.
        
        durum=ke.kitapEkle(ke);//durum u kitapEkle ye gönder.
        temizle();//temizle
        
         if(durum)
        {
            JOptionPane.showMessageDialog(this, "Veriler başarılı bir şekilde eklendi.");//ekrana uyarıyı yazdır
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Veriler Eklenemedi!.");//ekrana uyarıyı yazdır
        }
        
    }//GEN-LAST:event_btn_KaydetActionPerformed

    private void btn_BulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BulActionPerformed
        btn_Kaydet.setEnabled(false);//kaydet butonunu devre dışı bırak.
        btn_Guncelle.setEnabled(true);//güncelle butonunu aktif et
        btn_Sil.setEnabled(true);//sil butonunu aktif et
        boolean durum=false;//boolean veri türünde durum adında değişken tanımlayıp başlangıç değerini false yaptım.
        kitaplar kb=new kitaplar();//kitaplar sınıfında "kb" adında nesne oluşturdum.
        kb.setK_id(txt_id.getText());//"txt_id" oku "K_id" ya aktar.
        durum=kb.kitapBul(kb);//durum u kitapBul a gönder.
        
        txt_adi.setText(kb.getK_adi());// txt_adi a veri tabanındaki bilgiyi yaz
        txt_turu.setText(kb.getK_turu());// txt_turu ne veri tabanındaki bilgiyi yaz
        txt_yEvi.setText(kb.getK_yEvi());// txt_yEvi ne veri tabanındaki bilgiyi yaz
        txt_yazar.setText(kb.getK_yazar());// txt_yazar a veri tabanındaki bilgiyi yaz
        
        if(!durum)
        {
             JOptionPane.showMessageDialog(this, "Kayıt Bulunamadı.");//ekrana uyarıyı yazdır
            temizle();
        }
        
    }//GEN-LAST:event_btn_BulActionPerformed

    private void btn_SilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SilActionPerformed
        btn_Guncelle.setEnabled(false);//güncelle butonunu devre dışı bırak.
        btn_Sil.setEnabled(false);//sil butonunu devre dışı bırak.
        btn_Kaydet.setEnabled(true);//kaydet butonunu aktif et.
        btn_Bul.setEnabled(true);//bul butonunu aktif et.
        
        boolean durum=false;//boolean veri türünde durum adında değişken tanımlayıp başlangıç değerini false yaptım.
        
        kitaplar ks=new kitaplar();//kitaplar sınıfından "ks" adında nesne oluşturdum.
        ks.setK_id(txt_id.getText());//"txt_id" oku "K_id" ya aktar.
        durum=ks.kitapSil(ks);//durum u kitapSil e gönder.
        temizle();
        
         if(durum)
        {
            JOptionPane.showMessageDialog(this, "Veriler başarılı bir şekilde silindi.");//ekrana uyarıyı yazdır
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Veriler Silinemedi!.");//ekrana uyarıyı yazdır
        }
        
    }//GEN-LAST:event_btn_SilActionPerformed

    private void btn_GuncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_GuncelleActionPerformed
        btn_Guncelle.setEnabled(false);//güncelle butonunu devre dışı bırak.
        btn_Sil.setEnabled(false);//sil butonunu devre dışı bırak.
        btn_Bul.setEnabled(true);//bul butonunu aktif et.
        btn_Kaydet.setEnabled(true);//kaydet butonunu aktif et.
        
        boolean durum=false;//boolean veri türünde durum adında değişken tanımlayıp başlangıç değerini false yaptım.
        kitaplar kg=new kitaplar();//kitaplar sınıfında "kg" adında nesne oluşturdum.
        kg.setK_id(txt_id.getText());//"txt_id" oku "K_id" ya aktar.
        kg.setK_adi(txt_adi.getText());//"txt_adi" oku "K_adi" ya aktar.
        kg.setK_turu(txt_turu.getText());//"txt_turu" oku "K_turu" ya aktar.
        kg.setK_yEvi(txt_yEvi.getText());//"txt_yEvi" oku "K_yEvi" ya aktar.
        kg.setK_yazar(txt_yazar.getText());//"txt_yazar" oku "K_yazar" ya aktar.
        durum=kg.kitapGuncelle(kg);//durum u kitapGuncelle ye gönder.
        temizle();  
        
        if(durum)
        {
            JOptionPane.showMessageDialog(this, "Veriler başarılı bir şekilde güncellendi.");//ekrana uyarıyı yazdır
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Veriler Güncellenemedi!.");//ekrana uyarıyı yazdır
        }
    }//GEN-LAST:event_btn_GuncelleActionPerformed

    private void btn_MenuDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_MenuDonActionPerformed
        setVisible(false);//formu kapat
        new menu().setVisible(true);//menu formunu aç
    }//GEN-LAST:event_btn_MenuDonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kitapESG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kitapESG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kitapESG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kitapESG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kitapESG().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Bul;
    private javax.swing.JButton btn_Guncelle;
    private javax.swing.JButton btn_Kaydet;
    private javax.swing.JButton btn_MenuDon;
    private javax.swing.JButton btn_Sil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txt_adi;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_turu;
    private javax.swing.JTextField txt_yEvi;
    private javax.swing.JTextField txt_yazar;
    // End of variables declaration//GEN-END:variables
}
