/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.atakancetinkaya.arayuz;
import com.atakancetinkaya.siniflar.*;
import javax.swing.JOptionPane;

/**
 *
 * @author ataka
 */
public class uyeESG extends javax.swing.JFrame {

    /**
     * Creates new form uyeESG
     */
    public uyeESG() {
        initComponents();
        btn_Guncelle.setEnabled(false);
        btn_Sil.setEnabled(false);
        temizle();//temizle methodunu çalıştır.
    }
    
    public void temizle()
    {
        txt_Tc.setText("");//txt_Tc nin içini boşalt
        txt_AdSoyad.setText("");//txt_AdSoyad nin içini boşalt
        txt_Tel.setText("");//txt_Tel nin içini boşalt
        txt_Adres.setText("");//txt_Adres nin içini boşalt
        buttonGroup1.clearSelection();//seçimleri temizle
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_Tc = new javax.swing.JTextField();
        txt_AdSoyad = new javax.swing.JTextField();
        txt_Tel = new javax.swing.JTextField();
        rb_erkek = new javax.swing.JRadioButton();
        rb_kadın = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_Adres = new javax.swing.JTextArea();
        btn_Kaydet = new javax.swing.JButton();
        btn_Bul = new javax.swing.JButton();
        btn_Sil = new javax.swing.JButton();
        btn_Guncelle = new javax.swing.JButton();
        btn_MenuDon = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("TC No");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(160, 35, 35, 15);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Ad Soyad");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(140, 74, 59, 15);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Cinsiyet");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(150, 115, 48, 15);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Telefon No");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(140, 165, 65, 15);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Adres");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(160, 200, 35, 15);
        getContentPane().add(txt_Tc);
        txt_Tc.setBounds(210, 30, 199, 25);
        getContentPane().add(txt_AdSoyad);
        txt_AdSoyad.setBounds(210, 70, 199, 25);
        getContentPane().add(txt_Tel);
        txt_Tel.setBounds(220, 160, 199, 25);

        buttonGroup1.add(rb_erkek);
        rb_erkek.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rb_erkek.setText("Erkek");
        getContentPane().add(rb_erkek);
        rb_erkek.setBounds(220, 110, 59, 23);

        buttonGroup1.add(rb_kadın);
        rb_kadın.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rb_kadın.setText("Kadın");
        getContentPane().add(rb_kadın);
        rb_kadın.setBounds(290, 110, 59, 23);

        txt_Adres.setColumns(20);
        txt_Adres.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_Adres.setRows(5);
        jScrollPane1.setViewportView(txt_Adres);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(220, 200, 199, 107);

        btn_Kaydet.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_Kaydet.setIcon(new javax.swing.ImageIcon("C:\\Users\\ataka\\OneDrive\\Masaüstü\\KutuphaneOtomasyonu\\image\\add_30x30.jpg")); // NOI18N
        btn_Kaydet.setText("Kaydet");
        btn_Kaydet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_KaydetActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Kaydet);
        btn_Kaydet.setBounds(480, 30, 110, 64);

        btn_Bul.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_Bul.setIcon(new javax.swing.ImageIcon("C:\\Users\\ataka\\OneDrive\\Masaüstü\\KutuphaneOtomasyonu\\image\\search_30x30.jpg")); // NOI18N
        btn_Bul.setText("Bul");
        btn_Bul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BulActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Bul);
        btn_Bul.setBounds(600, 30, 117, 64);

        btn_Sil.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_Sil.setIcon(new javax.swing.ImageIcon("C:\\Users\\ataka\\OneDrive\\Masaüstü\\KutuphaneOtomasyonu\\image\\remove_30x30.jpg")); // NOI18N
        btn_Sil.setText("Sil");
        btn_Sil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SilActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Sil);
        btn_Sil.setBounds(480, 110, 109, 61);

        btn_Guncelle.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_Guncelle.setIcon(new javax.swing.ImageIcon("C:\\Users\\ataka\\OneDrive\\Masaüstü\\KutuphaneOtomasyonu\\image\\update_30x30.jpg")); // NOI18N
        btn_Guncelle.setText("Güncelle");
        btn_Guncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_GuncelleActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Guncelle);
        btn_Guncelle.setBounds(600, 110, 120, 61);

        btn_MenuDon.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_MenuDon.setIcon(new javax.swing.ImageIcon("C:\\Users\\ataka\\OneDrive\\Masaüstü\\KutuphaneOtomasyonu\\image\\back_30x30.jpg")); // NOI18N
        btn_MenuDon.setText("Menüye Dön");
        btn_MenuDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_MenuDonActionPerformed(evt);
            }
        });
        getContentPane().add(btn_MenuDon);
        btn_MenuDon.setBounds(520, 190, 143, 62);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/atakancetinkaya/arayuz/1_757x410.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 760, 410);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_KaydetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_KaydetActionPerformed
        boolean durum=false;//boolean veri türünde durum adında değişken tanımlayıp başlangıç değerini false yaptım.
        uyeler ue= new uyeler();//uyeler sınıfında "ue" adında nesne oluşturdum.
        ue.setU_tcNo(Long.valueOf(txt_Tc.getText()));//"txt_Tc" oku "U_tcNo" ya aktar.
        ue.setU_adSoyad(txt_AdSoyad.getText());//"txt_AdSoyad" oku "U_adSoyad" ya aktar.
        if (rb_erkek.isSelected()==true) //cinsiyet erkek seçili ise if içine gir
        {
            ue.setU_cinsiyet(true);//true yap
        }
        if(rb_kadın.isSelected()==true)
        {
            ue.setU_cinsiyet(false);//false yap
        }
        ue.setU_tel(txt_Tel.getText());//"txt_Tel" oku "U_tel" ya aktar.
        ue.setU_adres(txt_Adres.getText());//"txt_Adres" oku "U_adres" ya aktar.
        
        durum=ue.uyeEkle(ue);//durum u uyeEkle ye gönder.
        temizle();//temizle
        
         if(durum)
        {
            JOptionPane.showMessageDialog(this, "Veriler başarılı bir şekilde eklendi.");//ekrana uyarıyı yazdır
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Veriler Eklenemedi!.");//ekrana uyarıyı yazdır
        }
    }//GEN-LAST:event_btn_KaydetActionPerformed

    private void btn_BulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BulActionPerformed
        btn_Kaydet.setEnabled(false);//kaydet butonunu devre dışı bırak.
        btn_Guncelle.setEnabled(true);//güncelle butonunu aktif et
        btn_Sil.setEnabled(true);//sil butonunu aktif et
        boolean durum=false;//boolean veri türünde durum adında değişken tanımlayıp başlangıç değerini false yaptım.
        uyeler ub=new uyeler();//uyeler sınıfında "ub" adında nesne oluşturdum.
        ub.setU_tcNo(Long.valueOf(txt_Tc.getText()));//"txt_Tc" oku "U_tcNo" ya aktar.
        durum=ub.uyeBul(ub);//durum u uyeBul a gönder.
        
        txt_AdSoyad.setText(ub.getU_adSoyad());// txt_AdSoyad a veri tabanındaki bilgiyi yaz
        
        if(ub.isU_cinsiyet()==true)//cinsiyet tarafındaki bilgi 1 ise
        {
            rb_erkek.setSelected(true);//erkek seçilmiş olacak
        }
        if (ub.isU_cinsiyet()==false)//cinsiyet tarafındaki bilgi 0 ise
        {
           rb_kadın.setSelected(true);//kadın seçilmiş olacak
        }
        
        txt_Tel.setText(ub.getU_tel());// txt_Tel e veri tabanındaki bilgiyi yaz
        txt_Adres.setText(ub.getU_adres());// txt_Adres e veri tabanındaki bilgiyi yaz
        
        if(!durum)
        {
             JOptionPane.showMessageDialog(this, "Kayıt Bulunamadı.");//ekrana uyarıyı yazdır
            temizle();
        }
        
    }//GEN-LAST:event_btn_BulActionPerformed

    private void btn_SilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SilActionPerformed
        btn_Guncelle.setEnabled(false);//güncelle butonunu devre dışı bırak.
        btn_Sil.setEnabled(false);//sil butonunu devre dışı bırak.
        btn_Kaydet.setEnabled(true);//kaydet butonunu aktif et.
        btn_Bul.setEnabled(true);//bul butonunu aktif et.
        
        boolean durum=false;//boolean veri türünde durum adında değişken tanımlayıp başlangıç değerini false yaptım.
        
        uyeler us=new uyeler();//uyeler sınıfında "us" adında nesne oluşturdum.
        us.setU_tcNo(Long.valueOf(txt_Tc.getText()));//"txt_Tc" oku "U_tcNo" ya aktar.
        durum=us.uyeSil(us);//durum u uyeSil e gönder.
        temizle();
        
         if(durum)
        {
            JOptionPane.showMessageDialog(this, "Veriler başarılı bir şekilde silindi.");//ekrana uyarıyı yazdır
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Veriler Silinemedi!.");//ekrana uyarıyı yazdır
        }
        
    }//GEN-LAST:event_btn_SilActionPerformed

    private void btn_GuncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_GuncelleActionPerformed
        btn_Guncelle.setEnabled(false);//güncelle butonunu devre dışı bırak.
        btn_Sil.setEnabled(false);//sil butonunu devre dışı bırak.
        btn_Bul.setEnabled(true);//bul butonunu aktif et.
        btn_Kaydet.setEnabled(true);//kaydet butonunu aktif et.
        
        boolean durum=false;//boolean veri türünde durum adında değişken tanımlayıp başlangıç değerini false yaptım.
        uyeler ug=new uyeler();//uyeler sınıfında "ug" adında nesne oluşturdum.
        ug.setU_tcNo(Long.valueOf(txt_Tc.getText()));//"txt_Tc" oku "U_tcNo" ya aktar.
        ug.setU_adSoyad(txt_AdSoyad.getText());//"txt_AdSoyad" oku "U_adSoyad" ya aktar.
        if (rb_erkek.isSelected()==true) //cinsiyet erkek seçili ise if içine gir
        {
            ug.setU_cinsiyet(true);//true yap
        }
        if(rb_kadın.isSelected()==true)
        {
            ug.setU_cinsiyet(false);//false yap
        }
        ug.setU_tel(txt_Tel.getText());//"txt_Tel" oku "U_tel" ya aktar.
        ug.setU_adres(txt_Adres.getText());//"txt_Adres" oku "U_adres" ya aktar.
        durum=ug.uyeGuncelle(ug);//durum u uyeGuncelle ye gönder.
        temizle();  
        
        if(durum)
        {
            JOptionPane.showMessageDialog(this, "Veriler başarılı bir şekilde güncellendi.");//ekrana uyarıyı yazdır
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Veriler Güncellenemedi!.");//ekrana uyarıyı yazdır
        }
        
    }//GEN-LAST:event_btn_GuncelleActionPerformed

    private void btn_MenuDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_MenuDonActionPerformed
        setVisible(false);//formu kapat
        new menu().setVisible(true);//menu formunu aç
    }//GEN-LAST:event_btn_MenuDonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(uyeESG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(uyeESG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(uyeESG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(uyeESG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new uyeESG().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Bul;
    private javax.swing.JButton btn_Guncelle;
    private javax.swing.JButton btn_Kaydet;
    private javax.swing.JButton btn_MenuDon;
    private javax.swing.JButton btn_Sil;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rb_erkek;
    private javax.swing.JRadioButton rb_kadın;
    private javax.swing.JTextField txt_AdSoyad;
    private javax.swing.JTextArea txt_Adres;
    private javax.swing.JTextField txt_Tc;
    private javax.swing.JTextField txt_Tel;
    // End of variables declaration//GEN-END:variables
}
